env:
  - NO_CONFIRM=true

jobs:
  include:
    - stage: test
      language: elixir
      elixir: 1.8.2
      otp_release: 21.0
      before_script:
        - mix deps.get
      script:
        - mix test
        - mix hex.audit
        - mix dialyzer --plt
        - mix dialyzer --halt-exit-status
        - mix credo --strict
        - mix coveralls
      after_script:
        - MIX_ENV=test mix coveralls.travis
        - mix deps.get --only docs
        - MIX_ENV=docs mix inch.report
    - stage: prelude_test_osx
      install: true
      os: osx
      osx_image: xcode10.2
      script: ADIFY_TEST=true ./prelude.sh
    - stage: prelude_test_ubuntu
      install: true
      os: linux
      dist: trusty
      script: ADIFY_TEST=true ./prelude.sh
    - if: env(TRAVIS_COMMIT_MESSAGE) =~ [FULL_TEST_CI]
      stage: full_prelude_test_ubuntu
      install: true
      os: linux
      dist: trusty
      script: ./prelude.sh
    - if: env(TRAVIS_COMMIT_MESSAGE) =~ [FULL_TEST_CI]
      script: full_prelude_test_osx
      install: true
      os: osx
      osx_image: xcode10.2
      script: ./prelude.sh
