env:
  - CONFIRM=false

jobs:
  include:
    - stage: test
      language: elixir
      elixir: 1.8.2
      otp_release: 21.0
      before_script:
        - mix deps.get
      script: mix test
      after_script:
        - mix hex.audit
        - mix coveralls.travis
        - mix credo --strict
        - mix deps.get --only docs
        - MIX_ENV=docs mix inch.report
    - stage: prelude_test_osx
      os: osx
      osx_image: xcode10.2
      script: ./prelude.sh
    - stage: prelude_test_ubuntu
      os: linux
      dist: xenial
      script: ./prelude.sh
