language: elixir

elixir:
  - 1.9.0

otp_release:
  - 22.0

env:
  - CONFIRM=false

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
    - os: linux
      dist: xenial

jobs:
  include:
    - stage: script_test
      os: osx
      osx_image: xcode10.2
      script: ./adify.sh
